repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: end-of-file-fixer
        exclude: assets/js/instafeed.min.js
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.39.0
    hooks:
      - id: markdownlint
        types: ["markdown"]
        args: ["--fix"]
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.37.1
    hooks:
      - id: yamllint
        types: ["yaml"]
        args: ["--strict", "-d {rules: {document-start: disable, indentation: {spaces: 2}}}"]
  - repo: https://github.com/ComPWA/taplo-pre-commit
    rev: v0.9.3
    hooks:
      - id: taplo-lint
        types: ["toml"]
      - id: taplo-format
        types: ["toml"]
        args: ["--option", "indent_entries=true"]
  - repo: https://github.com/djlint/djLint
    rev: v1.36.4
    hooks:
      - id: djlint-reformat-golang
        types_or: ["html"]
        args: ["--indent", "2"]
      - id: djlint-golang
        types_or: ["html"]
        # H006: img tag should have height and width attributes.
        #   Images should be optimized in the future, but ignoring by now.
        # H016: Missing title tag in html.
        #   It is not missing, but included in another file.
        # H030: Consider adding a meta description.
        #   It is not missing, but included in another file.
        # H031: Consider adding meta keywords.
        #   They are not useful any more.
        args: ["--ignore", "H006,H016,H030,H031"]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0
    hooks:
      - id: prettier
        types_or: ["scss", "javascript"]
  - repo: https://github.com/thibaudcolas/pre-commit-stylelint
    rev: v16.20.0
    hooks:
      - id: stylelint
        types: ["scss"]
        args: ["--fix"]
        additional_dependencies:
          - stylelint@16.20.0
          - stylelint-config-standard-scss@15.0.1
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.28.0
    hooks:
      - id: eslint
        name: eslint (js only)
        types: ["javascript"]
        args: ["--fix", "--no-config-lookup"]
        additional_dependencies:
          - "eslint@9.28.0"
